<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>dc0d2710-4c0b-4893-b61f-6d8cc6e23edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRO2zTUBSGYzsJoapEBEvGDoiBKPEjKYRIkdpiN3XqB3nVOIjhxrlxrut3rpvGTGwVC0iIgbAAY8dOwM4SIdQRsSAxIiEhJkbihbkLw_mHcz790vn_mxRbZuvXh0MOcLACSsYmvF2qjhlQqtUgU1oNOx5VxgY7roZX1_Lv993m5_nZ1vOf397kXpiPF8QNExqefwQiDMBoyBnBkQEYhi17roOM0Jt6Y1w2POeUeDDB2J_Wadr2TOSW_10910YuTBgaQ_pibrS3IiYcnWgIp_47gjgniCdkmmUqlQWZgW6p331NEqdkIdivTR2JD7edtiRFjqzdKarNdqPxlbyibicmiXghiuFvMhNEMJwvqFdEFwMM74WeD0OM4LQB561et99GKmpVJY2NJU2ZAY3BhiPfUqyJrTaFWOb7WOdaSLnLMIOmYkmacKzHIlZiG8ncLpL5nYmuiTMRzdCBYAui5SV7R-VFVu2JWLeM-aDLMEp8uPIX44F1iPW4vSlbekXW2tUB3-dElzmjLhj5klqHDkD2xuoLF42-UMR36loAKlum7Q2BDY8NaCfceZr4kV5nqHout5ZPFVIbqT9p4m1m1bbwqWCcdD7uvZw9zC8fPU0tM3Tcw4NobkbF-3JH6MU6r3DqLj7we7UdcTQpdiM_6OwFXN-U5Ua1zj7LZn9lyZNLqQ-X_2f_fwE1&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWRO2zTUBSGYzsJoapEBEvGDoiBKPEjKYRIkdpiN3XqB3nVOIjhxrlxrut3rpvGTGwVC0iIgbAAY8dOwM4SIdQRsSAxIiEhJkbihbkLw_mHcz790vn_mxRbZuvXh0MOcLACSsYmvF2qjhlQqtUgU1oNOx5VxgY7roZX1_Lv993m5_nZ1vOf397kXpiPF8QNExqefwQiDMBoyBnBkQEYhi17roOM0Jt6Y1w2POeUeDDB2J_Wadr2TOSW_10910YuTBgaQ_pibrS3IiYcnWgIp_47gjgniCdkmmUqlQWZgW6p331NEqdkIdivTR2JD7edtiRFjqzdKarNdqPxlbyibicmiXghiuFvMhNEMJwvqFdEFwMM74WeD0OM4LQB561et99GKmpVJY2NJU2ZAY3BhiPfUqyJrTaFWOb7WOdaSLnLMIOmYkmacKzHIlZiG8ncLpL5nYmuiTMRzdCBYAui5SV7R-VFVu2JWLeM-aDLMEp8uPIX44F1iPW4vSlbekXW2tUB3-dElzmjLhj5klqHDkD2xuoLF42-UMR36loAKlum7Q2BDY8NaCfceZr4kV5nqHout5ZPFVIbqT9p4m1m1bbwqWCcdD7uvZw9zC8fPU0tM3Tcw4NobkbF-3JH6MU6r3DqLj7we7UdcTQpdiM_6OwFXN-U5Ua1zj7LZn9lyZNLqQ-X_2f_fwE1&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=qa3%40globalexcel.com')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
