<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Distance_on-off-switch-track-white</name>
   <tag></tag>
   <elementGuidId>9f4007a5-824b-4dd9-890d-f50d2309933f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='triageContent']/div/div/div/div/div[4]/div/div/div/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>on-off-switch-track-white</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;triageContent&quot;)/div[@class=&quot;row mainTriageRow  mh-100&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row  mh-100&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;on-off-switch&quot;]/div[@class=&quot;on-off-switch-track&quot;]/div[1]/div[@class=&quot;on-off-switch-track-off&quot;]/div[@class=&quot;on-off-switch-track-white&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='triageContent']/div/div/div/div/div[4]/div/div/div/div/div[2]/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
