<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>f43ef3c7-dace-4a9f-899e-f6f5fddb5e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cred_forgot_password_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cred_forgot_password_link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWSPWzTUBSFYzsJpapEVQmpYspQMYASP9tJCZEi8eMQ8mOH1E5MzMKL8-I8x_ZLnZcm8cqCUAfmgChi7AYTQioz6lSJBTEhRiZEl7LhLJ27MNyznE9HuufeG5yQEQpb3a4IRSTBtJVDt9LZPoDpfB6BdDRCvyf1LaGfDTZW18W_p-0370fy0f4X8evB040Fc91GFhntwQmFsNcVrd09CwIgZIjvYSsgY9KnGYt4h8yTAaWjcYHnXWJjP3PuEt_FPloyPEX8xdJ4EhEDkV9qgMajjwxzwjAv2LgAJGnBJpCfbmlvWeaQ3dTEENZqJaU06fM1c46r_uPbXrNY_M5eadxdhiyFBDhEf9jE7gQF8wX3itEopOhRQEYooBiNi2he1bVWEzdwNVs3hLBuqFNoAGp5yrbi2DPVM7FiNGnDUMIOBsCU217dKM1UuUXNyO-EVcd0KkB1BoMKnuJ2yS1VHIIV3cWqPMyqskVNWcl1NAA6horr-jBUwxJVyqanyjvDhq7MVV3JVXzwgbtg5cfcGvIgdlPRFj7ufeOYn9xVG3nSHdslXeiimYXcJRicxJlf8TXAFVZWVtdjm7FU7CzOvEtE96Zb5R_XUs8ar88-758eHcSOE_xUcuUynEc1btMsHWoPtCkB-XtY0GSv16zcdHech3oH8Pi-XRQKwstk8neSfX4p9uny__yAfw2&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=gem3%40globalexcel.comr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta_error_message_text&quot;)/div[@id=&quot;recover_container&quot;]/p[2]/a[@id=&quot;cred_forgot_password_link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cred_forgot_password_link']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recover_container']/p[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We don', &quot;'&quot;, 't recognize this user ID or password')])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a new sign-in experience!'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type the email address of the account you want to sign in with.'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to {0}'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://passwordreset.microsoftonline.com:443/?ru=https%3a%2f%2flogin.microsoftonline.com%2fgecopvautaadb2cqvca001.onmicrosoft.com%2freprocess%3fctx%3drQIIAbWSPWzTUBSFYzsJpapEVQmpYspQMYASP9tJCZEi8eMQ8mOH1E5MzMKL8-I8x_ZLnZcm8cqCUAfmgChi7AYTQioz6lSJBTEhRiZEl7LhLJ27MNyznE9HuufeG5yQEQpb3a4IRSTBtJVDt9LZPoDpfB6BdDRCvyf1LaGfDTZW18W_p-0370fy0f4X8evB040Fc91GFhntwQmFsNcVrd09CwIgZIjvYSsgY9KnGYt4h8yTAaWjcYHnXWJjP3PuEt_FPloyPEX8xdJ4EhEDkV9qgMajjwxzwjAv2LgAJGnBJpCfbmlvWeaQ3dTEENZqJaU06fM1c46r_uPbXrNY_M5eadxdhiyFBDhEf9jE7gQF8wX3itEopOhRQEYooBiNi2he1bVWEzdwNVs3hLBuqFNoAGp5yrbi2DPVM7FiNGnDUMIOBsCU217dKM1UuUXNyO-EVcd0KkB1BoMKnuJ2yS1VHIIV3cWqPMyqskVNWcl1NAA6horr-jBUwxJVyqanyjvDhq7MVV3JVXzwgbtg5cfcGvIgdlPRFj7ufeOYn9xVG3nSHdslXeiimYXcJRicxJlf8TXAFVZWVtdjm7FU7CzOvEtE96Zb5R_XUs8ar88-758eHcSOE_xUcuUynEc1btMsHWoPtCkB-XtY0GSv16zcdHech3oH8Pi-XRQKwstk8neSfX4p9uny__yAfw2&amp;mkt=en-US&amp;hosted=0&amp;device_platform=Windows+10&amp;nca=1&amp;domain_hint=gecopvautaadb2cqvca001.onmicrosoft.com&amp;username=gem3%40globalexcel.comr')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
